server:
  port: 8087
spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092  # kafka连接配置,ip+port(默认为9092)

    # 配置消息监听器
    listener:
      # 开启消息监听的手动确认模式
      ack-mode: manual

#自定义的配置
kafka:
  topic:
    name: helloTopic
  consumer:
    group: helloGroup2